authorName: FJJ
experimentName: TAKD_SHIP
trialConcurrency: 1
maxExecDuration: 48h
maxTrialNum: 1

#choice: local, remote, pai
trainingServicePlatform: local
searchSpacePath: search_space_ship.json
localConfig:
  useActiveGpu: true            #
  maxTrialNumPerGpu: 100        #
#choice: true, false
useAnnotation: false
#use_active_gpu: true
tuner:
  #choice: TPE, Random, Anneal, Evolution, BatchTuner
  #SMAC (SMAC should be installed through nnictl)
  builtinTunerName: TPE
  classArgs:
    #choice: maximize, minimize
    optimize_mode: maximize
trial:
  command: python train_ship.py --epochs 50 --cuda 1
  codeDir: .
  gpuNum: 1